### ISSUE TITLE
Issue related to Gurobi License

### ISSUE THREAD

**Issue by viewn** [omerbp/Best-Response-Regression#1]
After executed source code, we need to register Gurobi key?

I have registerd a free academic license on gurobi.com

After that, I have executed this command:
grbgetkey be849fc2-507a-11e8-87d8-0a4522cc772c 

Below is error log:

info  : grbgetkey version 8.0.0, build v8.0.0rc0
info  : Contacting Gurobi key server...
error : ERROR 303: hostname 183.80.1.1 (183.80.81.110) not recognized as belonging to an academic domain
info  : Is your computer connected to the university network?
info  : Your computer must be connected to the university network for the grbgetkey
info  : command to work. You can connect your computer either directly or via a VPN
info  : that tunnels all traffic through the university network.  Once the license is
info  : installed, your computer does not need to be connected to the university
info  : network. You can repeat this process to get licenses for additional computers.
info  : If you are unable to install this license, please contact key@gurobi.com for
info  : further assistance.

**Comment by omerbp** [comment]
Hi,
It seems to me the issue is concerned with Gurobi and not the particular piece of code. Therefore, I suggest you first try to run one of Gurobi's examples (e.g., [this one](http://www.gurobi.com/documentation/8.0/examples/lp_py.html)).
